version: '3.4'

services:
  
  # Database
  velosaurusdb:
    image: postgres
    restart: always
    container_name: velosaurus-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=velosaurus
    ports:
      - "5432:5432"
    volumes:
      - velosaurusdb:/var/lib/postgresql/data

    domainname: velosaurusdb
  
  
  # Service
  velosaurus-api:
    build:
      context: .
      dockerfile: /Dockerfile
    depends_on:
      - velosaurusdb
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=host=velosaurusdb;database=Tour;port=5432;username=postgres;password=password
  
  
  # PgAdmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8002:8001"
    depends_on:
      - velosaurusdb
    volumes:
      - pgadmin_vol:/var/lib/pgadmin


volumes:
  velosaurusdb:
  pgadmin_vol: