services:
  
  # Database
  velosaurusdb:
    image: postgres
    restart: always
    container_name: velosaurus-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=velosaurus
    ports:
      - "5432:5432"
    volumes:
      - velosaurus-data:/var/lib/postgresql/data
  
  
  # Service
  velosaurus-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: velosaurus-api
    depends_on:
      - velosaurusdb
    ports:
      - "8000:6789"  # 8000 is the port on host machine, 6789 is the port inside container
    environment:
      - ASPNETCORE_URLS=http://+:6789  # default asp.net core port is 8080 (since net8), other ports has to be specified here 
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ActivityDbConnectionString=Host=velosaurusdb; Database=velosaurus; Port=5432; User Id=postgres; Password=password
      - Serilog:WriteTo:0:Args:pathFormat=/logs/log-{Date}.txt
    
  
  # PgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: velosaurus-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8002:8001"
    depends_on:
      - velosaurusdb
    volumes:
      - pgadmin-vol:/var/lib/pgadmin
    links:
      - velosaurusdb
    


volumes:
  velosaurus-data:
  pgadmin-vol: