services:
  # Database
  velosaurusdb:
    image: postgres
    restart: always
    container_name: velosaurus-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=velosaurus
    ports:
      - "5433:5432" # only exposing to port 5433 on host, api service still listens to internal 5432 port
    volumes:
      - velosaurus-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5

  # REST API
  velosaurus-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: velosaurus-api
    container_name: velosaurus-api
    depends_on:
      - velosaurusdb
    ports:
      - "8000:6789" # 8000 is the port on host machine, 6789 is the port inside container
    environment:
      - ASPNETCORE_URLS=http://+:6789 # default asp.net core port is 8080 (since net8), other ports has to be specified here
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ActivityDbConnectionString=Host=velosaurusdb; Database=velosaurus; Port=5432; User Id=postgres; Password=password
      - Serilog:WriteTo:0:Args:pathFormat=/logs/log-{Date}.txt

volumes:
  velosaurus-data:
