version: '3.4'

services:
  
  # Database
  velosaurusdb:
    image: postgres
    restart: always
    container_name: velosaurus-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=velosaurus
    ports:
      - "5432:5432"
    volumes:
      - velosaurus-data:/var/lib/postgresql/data
  
  
  # Service
  velosaurus-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - velosaurusdb
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ActivityDbConnectionString=Host=velosaurusdb; Database=velosaurus; Port=5432; User Id=postgres; Password=password
      - Serilog:WriteTo:0:Args:pathFormat=/logs/log-{Date}.txt
    container_name: velosaurus-api
  
  
  # PgAdmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8002:8001"
    depends_on:
      - velosaurusdb
    volumes:
      - pgadmin-vol:/var/lib/pgadmin
    links:
      - velosaurusdb
    container_name: velosaurus-pgadmin


volumes:
  velosaurus-data:
  pgadmin-vol: