--
-- PostgreSQL database dump
--

\restrict uE4E1GgfHzasw1f4SFV6PKTGxSgMXzbHesLMpbgE9mYvQUS0ZoDG9svNRgUp8e9

-- Dumped from database version 18.6 (Debian 18.6-1.pgdg13+2)
-- Dumped by pg_dump version 18.6 (Debian 18.6-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public."Activities" DROP CONSTRAINT IF EXISTS "FK_Activities_Locations_LocationId";
DROP INDEX IF EXISTS public."IX_Activities_LocationId";
ALTER TABLE IF EXISTS ONLY public."__EFMigrationsHistory" DROP CONSTRAINT IF EXISTS "PK___EFMigrationsHistory";
ALTER TABLE IF EXISTS ONLY public."Locations" DROP CONSTRAINT IF EXISTS "PK_Locations";
ALTER TABLE IF EXISTS ONLY public."Activities" DROP CONSTRAINT IF EXISTS "PK_Activities";
DROP TABLE IF EXISTS public."__EFMigrationsHistory";
DROP TABLE IF EXISTS public."Locations";
DROP TABLE IF EXISTS public."Activities";
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Activities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Activities" (
    "Id" integer NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Length" real NOT NULL,
    "AltitudeGain" real NOT NULL,
    "ActivityType" integer NOT NULL,
    "Description" character varying(250) NOT NULL,
    "LocationId" integer
);


--
-- Name: Activities_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Activities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Activities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Locations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Locations" (
    "Id" integer NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Region" character varying(50)
);


--
-- Name: Locations_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Locations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Locations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: Activities; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Activities" ("Id", "Name", "Date", "Length", "AltitudeGain", "ActivityType", "Description", "LocationId") FROM stdin;
1	Bikepark Mutters	2026-07-05 10:00:00+00	14	750	0	Climb from Mutters to the Muttereralm and enjoy the bikepark lines and trails on the way down, with views over Innsbruck and the Nordkette.	1
2	Lanser Kopf and Paschberg	2026-08-23 08:30:00+00	18	420	0	Loop from Innsbruck over the Paschberg to Lanser Kopf and Lanser See, with short singletrails through the forest of the Mittelgebirge.	3
3	Arzler Alm Trail	2026-06-14 09:00:00+00	11	480	0	Uphill from Innsbruck on the forest road to Arzler Alm, then down the flowy Arzler Alm Trail with berms and small jumps back to the city.	2
\.


--
-- Data for Name: Locations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Locations" ("Id", "Name", "Region") FROM stdin;
1	Mutters	Stubaier Alpen
2	Innsbruck	Karwendel
3	Lans	Tuxer Alpen
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20241030202734_InitialMigration	10.0.12
\.


--
-- Name: Activities_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Activities_Id_seq"', 3, true);


--
-- Name: Locations_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Locations_Id_seq"', 3, true);


--
-- Name: Activities PK_Activities; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activities"
    ADD CONSTRAINT "PK_Activities" PRIMARY KEY ("Id");


--
-- Name: Locations PK_Locations; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Locations"
    ADD CONSTRAINT "PK_Locations" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Activities_LocationId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Activities_LocationId" ON public."Activities" USING btree ("LocationId");


--
-- Name: Activities FK_Activities_Locations_LocationId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Activities"
    ADD CONSTRAINT "FK_Activities_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES public."Locations"("Id");


--
-- PostgreSQL database dump complete
--

\unrestrict uE4E1GgfHzasw1f4SFV6PKTGxSgMXzbHesLMpbgE9mYvQUS0ZoDG9svNRgUp8e9

