name: Build, run unit tests and check dockerfile

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["9.x.x"]

    steps:
      - uses: actions/checkout@v4

      # =====================================================================================================
      # build and run unit tests

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Unit tests
        run: dotnet test --no-restore --verbosity normal

      # =====================================================================================================
      # Test docker compose file

      # Install Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Validate docker-compose file syntax
        run: docker-compose config --quiet && printf "OK\n" || printf "ERROR\n"

      - name: Set Up Docker Environment
        run: docker-compose -f docker-compose.yml up -d

      - name: Stop Containers
        run: docker-compose -f docker-compose.yml down
