# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build, UnitTest, Docker-check

on:
  push:
    branches:
      - main
      - "*"
    paths-ignore:
      - 'README.md'
  workflow_dispatch:  # for running manually in GitHub/actions view

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.x.x' ]

    steps:
      - uses: actions/checkout@v4
      

    # =====================================================================================================
    # substitute env vars and secrets

      #- uses: microsoft/variable-substitution@v1 
      #  with:
      #      files: '**/appsettings.json'
      #  env:
      #      TourDatabase.DbConnectionString: ${{ secrets.DBCONNECTIONSTRING }}
      #      App.ServerRootAddress: ${{ env.SERVER_ROOT_ADDRESS }}



    # =====================================================================================================
    # build and run unit tests

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Unit tests
        run: dotnet test --no-restore --verbosity normal
  

    # =====================================================================================================
    # Test docker compose file

      - name: Validate docker-compose file syntax
        run: docker-compose config --quiet && printf "OK\n" || printf "ERROR\n"

      - name: Set Up Docker Environment
        run: docker-compose -f docker-compose.yml up -d

      # - name: Wait for Docker to Finish Building
      #   run: sleep 30

      - name: Stop Containers
        run: docker-compose -f docker-compose.yml down




    # =====================================================================================================
    # publish and upload artifact

       # - name: dotnet publish
       #   run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
         
       # - name: Upload artifact for deployment job
       #   uses: actions/upload-artifact@v2
       #   with:
       #     name: .net-app
       #     path: ${{env.DOTNET_ROOT}}/myapp



    # =====================================================================================================
    # deploy:

  #  runs-on: ubuntu-latest
  #  needs: build
  #  environment:
  #    name: 'Production'
  #    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #  steps:
  #    - name: Download artifact from build job
  #      uses: actions/download-artifact@v2
  #      with:
  #        name: .net-app

  #    - name: Deploy to Azure Web App
  #      id: deploy-to-webapp
  #      uses: azure/webapps-deploy@v2
  #      with:
  #        app-name: 'velosaurus-api'
  #        slot-name: 'Production'
  #        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_878CCC60AA5E45ADB6925B6DAED8956B }}
  #        package: .
