name: Build and publish docker image

on:
  workflow_run:
    workflows: ["Build, run unit tests and check dockerfile"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-push_to_registry:
    if: ${{ github.event.workflow_run.head_branch == 'main' }}
    name: Build docker image and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dasmuesli/velosaurus-backend:latest

      - name: Docker Hub link
        run: echo "Docker image published to https://hub.docker.com/repository/docker/dasmuesli/velosaurus-backend"
