name: Publish Docker image

on:
  workflow_run:
    workflows: ["Build, UnitTest, Docker-check"]
    types:
      - completed
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:  # for running manually in github/actions view


jobs:
  push_to_registry:
    name: Build docker image and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dasmuesli/velosaurus-backend:latest

      - name: Docker Hub link
        run: echo "Docker image published to https://hub.docker.com/repository/docker/dasmuesli/velosaurus-backend"